title: Academic Research Group
tagline: Department of XXX, ETH Zurich
description: Academic group website for GitHub Pages
footer_text: ""
markdown: kramdown
theme: null
plugins: []
include:
  - assets
  - images
